---
apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: steam
      context: ./..
      ko: {}
      # docker:
      #   dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - "kube/*"
