---
name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '*.go'
      - go.mod
      - go.sum
  pull_request:
    paths:
      - '*.go'
      - go.mod
      - go.sum
      - .github/workflows/*.yaml

jobs:
  gotest:
    name: Go test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: go test -v ./...

  e2e:
    name: End to end test
    runs-on: ubuntu-20.04

    services:
      mosquitto:
        image: eclipse-mosquitto
        ports:
          - 1883:1883

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install mosquitto
        run: sudo apt-get install -y mosquitto-clients

      - name: Run module
        run: go run . &

      - name: Run end to end testing
        run: ./e2e.sh

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs:
      - gotest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'

      - name: GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13

      - name: Prepare
        id: prep
        run: |
          if [ "${{github.event_name}}" == "pull_request" ]; then
            echo ::set-output name=PUSH::false
          else
            echo ::set-output name=PUSH::true
          fi

          echo ::set-output name=GITVERSIONF::${GITVERSION_FULLSEMVER/+/-}

      - name: Setup ko
        uses: imjasonh/setup-ko@v0.4

      - name: Build local image
        run: >
          ko build --bare --platform linux/amd64,linux/arm64
          --sbom none --tags latest,${{ steps.prep.outputs.GITVERSIONF }} --push=false .
        if: ${{ steps.prep.outputs.PUSH == 'false' }}

      - name: Build and push image
        run: >
          ko build --bare --platform linux/amd64,linux/arm64
          --sbom none --tags latest,${{ steps.prep.outputs.GITVERSIONF }} .
        if: ${{ steps.prep.outputs.PUSH == 'true' }}
